# Capstone Bonus Questions

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
store_sales = pd.read_csv("StoreSales.csv")
store_detail = pd.read_csv("StoreDetail.csv")
products = pd.read_csv("Products.csv")
product_categories = pd.read_csv("ProductCategories.csv")
customer_list = pd.read_csv("customer_list.csv", sep="|")

In [6]:
store_sales["Transaction Date"] = pd.to_datetime(store_sales["Transaction Date"])

In [7]:
sales_data = store_sales.merge(store_detail, on="Store ID", how="inner")

In [8]:
south_sales = sales_data[
    sales_data["State"].isin(["Florida", "Texas"])
].copy()

## 1. Create a list of all transactions from January 2024, sorted by sale amount from highest to lowest. Which transactions had a sale amount greater than $500?

In [12]:
# transactions from Jan 2024
january_2024 = store_sales[
    store_sales["Transaction Date"].dt.strftime("%Y-%m") == "2024-01"
]

In [13]:
# Sort from highest to lowest
january_2024 = january_2024.sort_values(
    by="Sale Amount",
    ascending=False
)

january_2024

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
135133       2024-01-09       872        NaN  105341-IT       1763.7
134987       2024-01-09       731        NaN  105341-IT       1763.7
139709       2024-01-31       822        NaN  105341-IT       1763.7
138780       2024-01-27       736        NaN  105341-IT       1763.7
138720       2024-01-27       701        NaN  105341-IT       1763.7
...                 ...       ...        ...        ...          ...
139643       2024-01-31       736        NaN   105444-S          2.4
133337       2024-01-01       901      324.0   105402-S          2.4
138904       2024-01-27       850        NaN   105611-S          2.4
136726       2024-01-17       739        NaN   105444-S          2.4
138912       2024-01-27       853        NaN   105821-S          2.4

[6654 rows x 5 columns]

In [14]:
# Transactions higher then $500
high_sales = january_2024[
    january_2024["Sale Amount"] > 500
]

high_sales

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
135133       2024-01-09       872        NaN  105341-IT       1763.7
134987       2024-01-09       731        NaN  105341-IT       1763.7
139709       2024-01-31       822        NaN  105341-IT       1763.7
138780       2024-01-27       736        NaN  105341-IT       1763.7
138720       2024-01-27       701        NaN  105341-IT       1763.7
...                 ...       ...        ...        ...          ...
139274       2024-01-29       815        NaN  105262-IT        603.5
139391       2024-01-30       718        NaN  105262-IT        603.5
136360       2024-01-15       847        NaN  105262-IT        603.5
134154       2024-01-05       825        NaN  105262-IT        603.5
136218       2024-01-15       728        NaN  105262-IT        603.5

[497 rows x 5 columns]

# 2. Find all products whose product number begins with 10525. What category and subcategory do they belong to?