# Capstone Bonus Questions

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
store_sales = pd.read_csv("StoreSales.csv")
store_detail = pd.read_csv("StoreDetail.csv")
products = pd.read_csv("Products.csv")
product_categories = pd.read_csv("ProductCategories.csv")
customer_list = pd.read_csv("customer_list.csv", sep="|")

In [6]:
store_sales["Transaction Date"] = pd.to_datetime(store_sales["Transaction Date"])

In [7]:
sales_data = store_sales.merge(store_detail, on="Store ID", how="inner")

In [8]:
south_sales = sales_data[
    sales_data["State"].isin(["Florida", "Texas"])
].copy()

## 1. Create a list of all transactions from January 2024, sorted by sale amount from highest to lowest. Which transactions had a sale amount greater than $500?

In [12]:
# transactions from Jan 2024
january_2024 = store_sales[
    store_sales["Transaction Date"].dt.strftime("%Y-%m") == "2024-01"
]

In [13]:
# Sort from highest to lowest
january_2024 = january_2024.sort_values(
    by="Sale Amount",
    ascending=False
)

january_2024

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
135133       2024-01-09       872        NaN  105341-IT       1763.7
134987       2024-01-09       731        NaN  105341-IT       1763.7
139709       2024-01-31       822        NaN  105341-IT       1763.7
138780       2024-01-27       736        NaN  105341-IT       1763.7
138720       2024-01-27       701        NaN  105341-IT       1763.7
...                 ...       ...        ...        ...          ...
139643       2024-01-31       736        NaN   105444-S          2.4
133337       2024-01-01       901      324.0   105402-S          2.4
138904       2024-01-27       850        NaN   105611-S          2.4
136726       2024-01-17       739        NaN   105444-S          2.4
138912       2024-01-27       853        NaN   105821-S          2.4

[6654 rows x 5 columns]

In [14]:
# Transactions higher then $500
high_sales = january_2024[
    january_2024["Sale Amount"] > 500
]

high_sales

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
135133       2024-01-09       872        NaN  105341-IT       1763.7
134987       2024-01-09       731        NaN  105341-IT       1763.7
139709       2024-01-31       822        NaN  105341-IT       1763.7
138780       2024-01-27       736        NaN  105341-IT       1763.7
138720       2024-01-27       701        NaN  105341-IT       1763.7
...                 ...       ...        ...        ...          ...
139274       2024-01-29       815        NaN  105262-IT        603.5
139391       2024-01-30       718        NaN  105262-IT        603.5
136360       2024-01-15       847        NaN  105262-IT        603.5
134154       2024-01-05       825        NaN  105262-IT        603.5
136218       2024-01-15       728        NaN  105262-IT        603.5

[497 rows x 5 columns]

# 2. Find all products whose product number begins with 10525. What category and subcategory do they belong to?

In [15]:
# Product number begins with 10525
products_10525 = products[
    products["Prod Num"].astype(str).str.startswith("10525")
]

products_10525

     Prod Num                         Product  CategoryID SubcategoryID
2   105250-IT                      Realme Pad         120       120-tab
3   105251-IT              Lenovo Tab P12 Pro         120       120-tab
4   105252-IT         Microsoft Surface Pro 9         120       120-tab
5   105253-IT  Apple iPad Pro (12.9-inch, M2)         120       120-tab
6   105254-IT                 Chuwi HiPad Max         120       120-tab
7   105255-IT           Lenovo Yoga Smart Tab         120       120-tab
8   105256-IT     ASUS Vivobook 13 Slate OLED         120       120-tab
9   105257-IT     Samsung Galaxy Tab S9 Ultra         120       120-tab
10  105258-IT      Apple iPad Air (10.9-inch)         120       120-tab
11  105259-IT                 Teclast T40 Pro         120       120-tab

In [16]:
# Merge with category information
products_10525 = products_10525.merge(
    product_categories,
    on=["CategoryID", "SubcategoryID"],
    how="inner"
)

products_10525[
    ["Prod Num", "Category", "Subcategory"]
]

    Prod Num                  Category Subcategory
0  105250-IT  Technology & Accessories     Tablets
1  105251-IT  Technology & Accessories     Tablets
2  105252-IT  Technology & Accessories     Tablets
3  105253-IT  Technology & Accessories     Tablets
4  105254-IT  Technology & Accessories     Tablets
5  105255-IT  Technology & Accessories     Tablets
6  105256-IT  Technology & Accessories     Tablets
7  105257-IT  Technology & Accessories     Tablets
8  105258-IT  Technology & Accessories     Tablets
9  105259-IT  Technology & Accessories     Tablets

# 3. Which stores in your assigned territories had at least one transaction with a sale amount over $1,000? How many such transactions did each store have?

In [17]:
# Find transactions greater than $1,000
high_sales = south_sales[
    south_sales["Sale Amount"] > 1000
]

high_sales

,Transaction Date,Store ID,RewardsID,Prod Num,Sale Amount,Store Location,State,Territory Manager,Region,Region Director
138,2022-01-01,904,NaN,105326-IT,1717.70,Baytown,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
143,2022-01-01,908,328.0,105337-IT,1301.88,Denton,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
943,2022-01-07,723,NaN,105337-IT,1301.88,Lakeland,Florida,Lana Ilana,South,Andy Gisselquist
1090,2022-01-08,728,NaN,105340-IT,1291.71,Tallahassee,Florida,Lana Ilana,South,Andy Gisselquist
1094,2022-01-08,729,NaN,105335-IT,1257.12,Tampa,Florida,Lana Ilana,South,Andy Gisselquist
...,...,...,...,...,...,...,...,...,...,...
333910,2025-12-28,721,NaN,105335-IT,1257.12,Jacksonville,Florida,Lana Ilana,South,Andy Gisselquist
334210,2025-12-29,721,340.0,105330-IT,1376.44,Jacksonville,Florida,Lana Ilana,South,Andy Gisselquist
334488,2025-12-29,904,NaN,105326-IT,1717.70,Baytown,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
334863,2025-12-31,727,NaN,105333-IT,1292.00,Sebring,Florida,Lana Ilana,South,Andy Gisselquist
335120,2025-12-31,908,114.0,105343-IT,1257.12,Denton,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist

In [18]:
# Count transactions over $1,000 by store
high_sales_summary = high_sales.groupby(
    ["State", "Store ID", "Store Location"]
).size().reset_index(name="Transactions Over 1000")

high_sales_summary

      State  Store ID   Store Location  Transactions Over 1000
0   Florida       719   Cape Canaveral                      91
1   Florida       720  Fort Lauderdale                      87
2   Florida       721     Jacksonville                     105
3   Florida       722         Key West                      92
4   Florida       723         Lakeland                      66
5   Florida       724            Miami                     161
6   Florida       725           Naples                      65
7   Florida       726          Orlando                      84
8   Florida       727          Sebring                     102
9   Florida       728      Tallahassee                     139
10  Florida       729            Tampa                      79
11    Texas       901        Arlington                      74
12    Texas       902           Austin                      84
13    Texas       903          Bacliff                      71
14    Texas       904          Baytown                      73
15    Texas       905         Beaumont                     183
16    Texas       906       Cedar Park                      80
17    Texas       907           Dallas                      11
18    Texas       908           Denton                      82
19    Texas       909           Desoto                      81
20    Texas       910       Fort Worth                     114
21    Texas       911       Georgetown                      69